### ISSUE TITLE
Linked List code in C++

### ISSUE THREAD

**Issue by Praddyumn16** [amanmehara/programming#109]
I have created a pull request for Clockwise Rotation of a Linked List #108 
Since I did not find any folder for Linked List, hence I created this issue.

**Comment by amanmehara** [comment]
Closing in favor of #78.

Thank you for showing interest in contributing. 😃
@Praddyumn16 please create a PR having the algorithms implemented, I'll merge them.

Also have a look at: https://github.com/amanmehara/programming/blob/master/CONTRIBUTING.md
