### ISSUE TITLE
Add Scheduling Algorithms in Java

### ISSUE THREAD

**Issue by jinicode** [amanmehara/programming#110]
I would love to add solution to this.
Please assign me this issue and add hacktoberfest label.

**Comment by jinicode** [comment]
I have created a pull request #111 . Please and merge .

**Comment by amanmehara** [comment]
Closing in favor of #80.

Thank you for showing interest in contributing. 😃
@jinicode please create a PR having the algorithms implemented, I'll merge them.

Also have a look at: https://github.com/amanmehara/programming/blob/master/CONTRIBUTING.md
