### ISSUE TITLE
Add parenthesis checker and josephus proble in java.

### ISSUE THREAD

**Issue by jinicode** [amanmehara/programming#114]
Please assign this issue to me and add hacktober label.
Happy Hacking.

**Comment by jinicode** [comment]
Please add labels so that I can send PR asap . Thank You!!

**Comment by amanmehara** [comment]
Closing in favor of #80 .

Thank you for showing interest in contributing. 😃
@jinicode please create a PR having the algorithms implemented, I'll merge them.
**(Please don't create new issues, simply create a PR)**

Also have a look at: https://github.com/amanmehara/programming/blob/master/CONTRIBUTING.md
