### ISSUE TITLE
Add binary search tree and binary heap implementation in python.

### ISSUE THREAD

**Issue by jinicode** [amanmehara/programming#115]
Please assign this issue to me and add hacktober label.
Happy Hacking.

**Comment by amanmehara** [comment]
Closing in favor of #40.

Thank you for showing interest in contributing. 😃
@jinicode please create a PR having the algorithms implemented, I'll merge them.
**(Please do not create new issues, simply create a PR)**

Also have a look at: https://github.com/amanmehara/programming/blob/master/CONTRIBUTING.md
