### ISSUE TITLE
Infix to Postfix Conversion in C

### ISSUE THREAD

**Issue by Ramjonchhen** [amanmehara/programming#121]
I would like to work on infix to postfix using c can i contribute ?

**Comment by Ramjonchhen** [comment]
Hello @amanmehara  can i work on this issue?

**Comment by amanmehara** [comment]
Closing in favor of #56.

Thank you for showing interest in contributing. 😃
@Ramjonchhen  please create a PR having the algorithms implemented, I'll merge them.

Also have a look at: https://github.com/amanmehara/programming/blob/master/CONTRIBUTING.md
