### ISSUE TITLE
Binary Tree traversals in java

### ISSUE THREAD

**Issue by Vanshikaa00** [amanmehara/programming#125]
Hello @amanmehara  i would like to add a solution for this in java. I am participating in HacktoberFest , so could you please assign this issue to me

**Comment by amanmehara** [comment]
Closing in favor of #80 .

Thank you for showing interest in contributing. 😃
@Vanshikaa00  please create a PR having the algorithms implemented, I'll merge them.

Also have a look at: https://github.com/amanmehara/programming/blob/master/CONTRIBUTING.md
