### ISSUE TITLE
Binary Tree Views in Java

### ISSUE THREAD

**Issue by Vanshikaa00** [amanmehara/programming#126]
Hey @amanmehara i would like to work upon this issue .Can you please assign this to me :)

**Comment by amanmehara** [comment]
Closing in favor of #80.

Thank you for showing interest in contributing. 😃
@Vanshikaa00 please create a PR having the algorithms implemented, I'll merge them.

Also have a look at: https://github.com/amanmehara/programming/blob/master/CONTRIBUTING.md
