### ISSUE TITLE
Implementation of Dijkstra's algorithm to find shortest route in a weighted graph, c++

### ISSUE THREAD

**Issue by utkarshbajaj** [amanmehara/programming#81]
I would like to work on this in the Graphs directory, for Hacktoberfest!
I can work on Prims Algo for Minimum spanning tree too.

**Comment by amanmehara** [comment]
Hi @utkarshbajaj 

Definitely, contribute the Dijkstra's algorithms.
Create the PR for the same, I'll review and merge it.

Regarding minimum spanning tree @rafu01 is also planning to add them. You can discuss this with him directly.

Also have a look at https://github.com/amanmehara/programming/blob/master/CONTRIBUTING.md and make changes accordingly.
I'll approve and merge afterwards! 😃

**Comment by Roshan13046** [comment]
Please check the PR and suggest it.

**Comment by amanmehara** [comment]
Closing in favor of #78.

Thank you for showing interest in contributing. 😃
Please create a PR having the algorithms implemented, I'll merge them.

Also have a look at: https://github.com/amanmehara/programming/blob/master/CONTRIBUTING.md

**Comment by Roshan13046** [comment]
> Closing in favor of #78.
> 
> Thank you for showing interest in contributing. 😃
> Please create a PR having the algorithms implemented, I'll merge them.
> 
> Also have a look at: https://github.com/amanmehara/programming/blob/master/CONTRIBUTING.md

Thanks! for accepting my PR.
