### ISSUE TITLE
Implement Kruskal and Prims algorithm to find minimum spanning tree in C++

### ISSUE THREAD

**Issue by rafu01** [amanmehara/programming#90]
I did not find any MST algorithm implemented in c++.

**Comment by rafu01** [comment]
I would like to work on this as hacktober fest

**Comment by amanmehara** [comment]
Hi @rafu01 

Definitely, contribute the minimum spanning tree algorithms.
Create the PR for the same, I'll review and merge it.

Also have a look at https://github.com/amanmehara/programming/blob/master/CONTRIBUTING.md and make changes accordingly.
I'll approve and merge afterwards! 😃

**Comment by rafu01** [comment]
thanks, I'm working on it

**Comment by rafu01** [comment]
done, check #128

**Comment by amanmehara** [comment]
Closing in favor of #78.
