### ISSUE TITLE
Add search algorithms to Python. 

### ISSUE THREAD

**Issue by SDakshit** [amanmehara/programming#96]

**Comment by SDakshit** [comment]
I would like to work on this for hacktoberfest

**Comment by amanmehara** [comment]
Closing in favor of #40 .

Thank you for showing interest in contributing. 😃
@SDakshit please create a PR having the algorithms implemented, I'll merge them.

Also have a look at: https://github.com/amanmehara/programming/blob/master/CONTRIBUTING.md
