### ISSUE TITLE
Add scheduling algorithms in java.

### ISSUE THREAD

**Issue by jinicode** [amanmehara/programming#97]
Please assign this issue to me and I would love to work on this for hacktoberfest.
Happy Hacking.

**Comment by amanmehara** [comment]
Closing in favor of #80 .

Thank you for showing interest in contributing. 😃
@jinicode please create a PR having the algorithms implemented, I'll merge them.

Also have a look at: https://github.com/amanmehara/programming/blob/master/CONTRIBUTING.md
